# List of all valid gym exercises and the muscle groups they target
exercises = {
    "Bench Press": ["Chest", "Triceps", "Shoulders"],
    "Squat": ["Quadriceps", "Hamstrings", "Glutes", "Calves"],
    "Deadlift": ["Lower Back", "Hamstrings", "Glutes", "Forearms"],
    "Overhead Barbell Press": ["Shoulders", "Triceps"],
    "Barbell Row": ["Back", "Biceps", "Forearms"],
    "Pull-up": ["Back", "Biceps", "Forearms"],
    "Curl (barbell)": ["Biceps", "Forearms"],
    "Tricep Extension (machine)": ["Triceps"],
    "Leg Press": ["Quadriceps", "Hamstrings", "Glutes", "Calves"],
    "Leg Curl": ["Hamstrings"],
    "Leg Extension": ["Quadriceps"],
    "Calf Raise": ["Calves"],
    "Abdominal Crunch": ["Abs"],
    "Back Extension": ["Lower Back"],
    "Plank": ["Abs"],
    "Side Plank": ["Abs"],
    "Russian Twist": ["Abs"],
    "Lateral Raise": ["Shoulders"],
    "Front Raise": ["Shoulders"],
    "Reverse Fly": ["Shoulders"],
    "Shrug": ["Traps"],
    "Leg Raise": ["Abs"],
    "Glute Bridge": ["Glutes"],
    "Hip Thrust": ["Glutes"],
    "Hammer Curl": ["Biceps", "Forearms"],
    "Tricep Pushdown": ["Triceps"],
    "Dumbbell Curl": ["Biceps", "Forearms"],
    "Butterfly": ["Chest"],
    "Incline Dumbbell Press": ["Chest", "Triceps", "Shoulders"],
    "Skullcrusher": ["Triceps"],
    "Dumbbell Row": ["Back", "Biceps", "Forearms"],
    "Lat Pulldown": ["Back", "Biceps", "Forearms"],
    "Seated Row": ["Back", "Biceps", "Forearms"],
    "Leg Press (calf press)": ["Calves"],
    "Leg Press (hamstring press)": ["Hamstrings"],
    "Leg Press (quad press)": ["Quadriceps"],
    "Leg Curl (seated)": ["Hamstrings"],
    "Leg Curl (standing)": ["Hamstrings"],
    "Leg Extension (seated)": ["Quadriceps"],
    "Leg Extension (standing)": ["Quadriceps"],
    "Calf Raise (seated)": ["Calves"],
    "Calf Raise (standing)": ["Calves"],
    "Ab Roller": ["Abs"],
    "Sit-up": ["Abs"],
    "Crunch (machine)": ["Abs"],
    "Back Extension (machine)": ["Lower Back"],
    "Plank (side)": ["Abs"],
    "Russian Twist (with weight)": ["Abs"],
    "Lateral Raise (cable)": ["Shoulders"],
    "Front Raise (cable)": ["Shoulders"],
    "Reverse Fly (cable)": ["Shoulders"],
    "Reverse Butterfly": ["Shoulders"],
    "Seated Back Pull": ["Back", "Biceps", "Forearms"],
    "Toe Touch": ["Abs"],
}
